### ISSUE TITLE
Is not compatible with abstract-blob-store

### ISSUE THREAD

**Issue by examosa** [max-mapper/google-cloud-storage#2]
The current implementation of this store is not compatible with `abstract-blob-store` as it still uses `options.name` in many places instead of `options.key`.

**Comment by MichaelErmer** [comment]
Had the same issue, will open a PR.
You can use my fork just `npm i github:MichaelErmer/google-cloud-storage` until its merged

**Comment by examosa** [comment]
@MichaelErmer I went ahead and made my own fork and rewrote [this](https://github.com/Teomik129/gcs-blob-store) in TypeScript. I see you're a feathersjs enthusiast, which is coincidentally what I wanted to use this for. Cheers!
